.TH "TANGLE\-APP" "" "January 2014" "" ""
.SH "NAME"
\fBtangle-app\fR
.QP
.P
Tools for working with tangle apps

.
.SH Usage
.P
.RS 2
.EX
\-\-option, \-o [String] \- An example option\.
\-\-help, \-h \- Display this message
.EE
.RE
.SH Examples
.P
.RS 2
.EX
# Executing app with no options
$ tangle\-app
.EE
.RE